<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minibot_light_01">
  <xacro:property name="body_d" value="0.24" />
  <xacro:property name="body_w" value="0.24" />
  <xacro:property name="body_h" value="0.158" />
  <xacro:property name="body_offset_x" value="-0.05" />
  <xacro:property name="body_offset_z" value="${body_h/2}" />

  <link name="base_link">
    <collision>
      <origin rpy="0 0 0" xyz="${body_offset_x} 0 ${body_offset_z}"/>
      <geometry>
        <box size="${body_d} ${body_w} ${body_h}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="${body_offset_x} 0 ${body_offset_z}"/>
      <geometry>
        <box size="${body_d} ${body_w} ${body_h}"/>
      </geometry>
      <material name="vehicle_mat">
        <color rgba="1.0 0.0 0.0 0.5"/>
      </material>
    </visual>
  </link>

  <xacro:property name="laser_d" value="0.06" />
  <xacro:property name="laser_w" value="0.06" />
  <xacro:property name="laser_h" value="0.06" />
  <xacro:property name="laser_x" value="0.03" />
  <xacro:property name="laser_z" value="0.0787" />

  <joint name="laser_joint" type="fixed">
    <origin xyz="${laser_x} 0 ${laser_z}" rpy="0 0 ${radians(-90)}"/>
    <parent link="base_link"/>
    <child link="base_laser_link"/>
  </joint>

  <link name="base_laser_link">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${laser_d} ${laser_w} ${laser_h}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${laser_d} ${laser_w} ${laser_h}"/>
      </geometry>
      <material name="laser_mat">
        <color rgba="0.0 0.0 0.0 0.8"/>
      </material>
    </visual>
  </link>
</robot>
