<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minibot_light_01">
  <xacro:property name="body_d" value="0.315" />
  <xacro:property name="body_w" value="0.2423" />
  <xacro:property name="body_h" value="0.162" />
  <xacro:property name="body_offset_x" value="${0.07-body_d/2}" />
  <xacro:property name="body_offset_z" value="${body_h/2}" />

  <link name="base_link">
    <collision>
      <origin rpy="0 0 0" xyz="${body_offset_x} 0 ${body_offset_z}"/>
      <geometry>
        <box size="${body_d} ${body_w} ${body_h}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="${body_offset_x} 0 ${body_offset_z}"/>
      <geometry>
        <box size="${body_d} ${body_w} ${body_h}"/>
      </geometry>
      <material name="vehicle_mat">
        <color rgba="1.0 0.0 0.0 0.5"/>
      </material>
    </visual>
  </link>

  <xacro:property name="laser_d" value="0.06" />
  <xacro:property name="laser_w" value="0.06" />
  <xacro:property name="laser_h" value="0.06" />
  <xacro:property name="laser_x" value="0.04" />
  <xacro:property name="laser_z" value="0.01" />

  <joint name="laser_joint" type="fixed">
    <origin xyz="${laser_x} 0 ${laser_z}" rpy="${radians(180)} 0 0"/>
    <parent link="base_link"/>
    <child link="base_laser_link"/>
  </joint>

  <link name="base_laser_link">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${laser_d} ${laser_w} ${laser_h}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${laser_d} ${laser_w} ${laser_h}"/>
      </geometry>
      <material name="laser_mat">
        <color rgba="0.0 0.0 0.0 0.8"/>
      </material>
    </visual>
  </link>
</robot>
